#!/bin/bash
echo $(( $(echo $WATER | tr 'water' '01234' | tr -d '\n' | awk '{print "ibase=5;"$1}' | bc) + $(echo $STIR | tr 'stir' '0123' | tr -d '\n' | awk '{print "ibase=4;"$1}' | bc) )) | awk '{print "obase=8;"$1}' | bc | tr '01234567' 'bestchol'
